[package]
name = "bruh"
version = "0.1.0"
authors = ["Wafelack <wafelack@protonmail.com>"]
edition = "2018"
description = "Homebruh is package manager for GNU/Linux"
repository = "https://github.com/wafelack/homebruh"
readme = "README.md"
license = "GPL-3.0"
keywords = ["package-manager", "Homebruh", "bruh", "linux"]

[dependencies]
toml = "0.5.8"
flate2 = "1.0.20"
tar = "0.4.32"
reqwest = { version = "0.11", default-features = false, features = ["blocking"] }
sha2 = "0.9.3"
directories = ">=3.0.0"
bytes = ">=1.0.0"